Event/2023orsal
flamingchickens1540/pesto pull request #33
Opened 2023-03-31 22:50 UTC by rutmanz

2023-04-01 06:31 UTC, mimizh2418 requested changes
Fix the pivot constants and inversions because the belt is on now. Otherwise looks good.

2023-04-01 06:31 UTC, mimizh2418 commented on src/main/java/org/team1540/robot2023/Constants.java
> +        public static final int PIVOT2_ID = 10;
swap these back around

2023-04-01 06:31 UTC, mimizh2418 commented on src/main/java/org/team1540/robot2023/commands/arm/Arm.java
> +        pivot1.setInverted(false);
invert these again

2023-04-01 11:36 UTC, rutmanz commented
> Fix the pivot constants and inversions because the belt is on now. Otherwise looks good.

Does it actually matter? Ideally we make a way at some point to swap them mid-match, but I can't see a reason that one configuration would be preferred over the other

2023-04-02 17:53 UTC, mimizh2418 commented
> > Fix the pivot constants and inversions because the belt is on now. Otherwise looks good.
> 
> Does it actually matter? Ideally we make a way at some point to swap them mid-match, but I can't see a reason that one configuration would be preferred over the other

I guess it doesn't matter, I just find it unsettling. I do agree that we should at some point make a button that switches the drive motor though.

2023-04-02 17:53 UTC, mimizh2418 approved these changes

2023-04-14 02:07 UTC, closed without merging